debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.checklist: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jbdc:mysql://localhost:3306/checklist
    username: mok
    password: thisisTestpw!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
